PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 MODULE VIM_SUPPRESS_LISTE.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 MODULE LISTE_AFTER_LOOP.
