PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZLLM_CLNT_CONFIG-MODEL .
    FIELD ZLLM_CLNT_CONFIG-PROVIDER .
    FIELD ZLLM_CLNT_CONFIG-PROVIDER_MODEL .
    FIELD ZLLM_CLNT_CONFIG-STRUCTURED_OUTPUT .
    FIELD ZLLM_CLNT_CONFIG-TOOLS .
    FIELD ZLLM_CLNT_CONFIG-RFC_DESTINATION .
    FIELD ZLLM_CLNT_CONFIG-DEFAULT_OP .
    FIELD ZLLM_CLNT_CONFIG-FORCED_OP .
    FIELD ZLLM_CLNT_CONFIG-AUTH_TYPE .
    FIELD ZLLM_CLNT_CONFIG-AUTH_VALUE .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZLLM_CLNT_CONFIG-MODEL .
  module detail_pai.
 endchain.
