PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZLLM_CLNT_CONFIG CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZLLM_CLNT_CONFIG-MODEL .
    FIELD ZLLM_CLNT_CONFIG-PROVIDER_NAME .
    FIELD ZLLM_CLNT_CONFIG-PROVIDER_MODEL .
    FIELD ZLLM_CLNT_CONFIG-SUPPORT_SO .
    FIELD ZLLM_CLNT_CONFIG-SUPPORT_TOOLS .
    FIELD ZLLM_CLNT_CONFIG-DEFAULT_OP .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZLLM_CLNT_CONFIG-MODEL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
