PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZLLM_CLNT_CONFIG-MODEL .
    FIELD ZLLM_CLNT_CONFIG-PROVIDER_NAME .
    FIELD ZLLM_CLNT_CONFIG-PROVIDER_MODEL .
    FIELD ZLLM_CLNT_CONFIG-SUPPORT_SO .
    FIELD ZLLM_CLNT_CONFIG-SUPPORT_TOOLS .
    FIELD ZLLM_CLNT_CONFIG-DEFAULT_OP .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZLLM_CLNT_CONFIG-MODEL .
  module detail_pai.
 endchain.
